# Compilador
CC = gcc

# Flags de compilación
CFLAGS = -Wall -Wextra -Wpedantic -g -mwindows

# Flags de enlace
LDFLAGS = -lws2_32 -lgdi32

# Directorios
SRC_DIR = code
RES_DIR = resources
DATA_DIR = data
MENU_DIR = menus

# Fuentes y objetos
SRCS = $(wildcard $(SRC_DIR)/*.c $(DATA_DIR)/*.c $(RES_DIR)/*.c $(SRC_DIR)/$(MENU_DIR)/*.c) main.c
OBJS = $(SRCS:.c=.o)

# Target
TARGET = lunar_lander.exe

all: $(TARGET)

$(TARGET): $(OBJS)
	$(CC) $(OBJS) $(LDFLAGS) -o $@

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	del /Q $(SRC_DIR)\*.o $(DATA_DIR)\*.o $(RES_DIR)\*.o $(SRC_DIR)\$(MENU_DIR)\*.o main.o 2>nul

run:
	mingw32-make -f MakeFile clean
	mingw32-make -f MakeFile
	./lunar_lander.exe
	
